# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=20)),
                ('bulan', models.CharField(max_length=20)),
                ('tanggal', models.CharField(max_length=10)),
                ('body', models.TextField()),
            ],
        ),
    ]
