# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postModel2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=20)),
                ('tanggal', models.CharField(max_length=10)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='postModel',
        ),
    ]
