# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200811_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel2020',
            name='tanggal',
            field=models.CharField(max_length=2),
        ),
    ]
