# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200812_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postModel2020',
            new_name='postModel',
        ),
    ]
