# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200812_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='tahun',
            field=models.CharField(default='2020', max_length=20),
            preserve_default=False,
        ),
    ]
