# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('matakuliah', models.CharField(max_length=20)),
                ('pertemuan1', models.FileField(upload_to='')),
                ('pertemuan2', models.FileField(upload_to='')),
                ('pertemuan3', models.FileField(upload_to='')),
                ('pertemuan4', models.FileField(upload_to='')),
                ('pertemuan5', models.FileField(upload_to='')),
                ('pertemuan6', models.FileField(upload_to='')),
                ('pertemuan7', models.FileField(upload_to='')),
                ('pertemuan8', models.FileField(upload_to='')),
                ('pertemuan9', models.FileField(upload_to='')),
                ('pertemuan10', models.FileField(upload_to='')),
                ('pertemuan11', models.FileField(upload_to='')),
                ('pertemuan12', models.FileField(upload_to='')),
                ('pertemuan13', models.FileField(upload_to='')),
                ('pertemuan14', models.FileField(upload_to='')),
                ('pertemuan15', models.FileField(upload_to='')),
                ('pertemuan16', models.FileField(upload_to='')),
            ],
        ),
    ]
