# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan1',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan10',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan11',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan12',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan13',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan14',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan15',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan16',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan2',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan3',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan4',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan5',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan6',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan7',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan8',
            field=models.FileField(blank=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pertemuan9',
            field=models.FileField(blank=True, upload_to='document'),
        ),
    ]
