# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0003_auto_20200815_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan1',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan10',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan11',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan12',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan13',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan14',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan15',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan16',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan2',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan3',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan4',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan5',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan6',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan7',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan8',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='pertemuan9',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Pertemuan',
            field=models.CharField(choices=[('Pertemuan1', 'Pertemuan1'), ('Pertemuan2', 'Pertemuan2')], default='Pertemuan1', max_length=20),
        ),
    ]
