# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-23 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0004_auto_20200923_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='Pertemuan',
            field=models.CharField(choices=[('Pertemuan1', 'Pertemuan1'), ('Pertemuan2', 'Pertemuan2'), ('Pertemuan3', 'Pertemuan3'), ('Pertemuan4', 'Pertemuan4'), ('Pertemuan5', 'Pertemuan5'), ('Pertemuan6', 'Pertemuan6'), ('Pertemuan7', 'Pertemuan7'), ('Pertemuan8', 'Pertemuan8'), ('Pertemuan9', 'Pertemuan9'), ('Pertemuan10', 'Pertemuan10'), ('Pertemuan11', 'Pertemuan11'), ('Pertemuan12', 'Pertemuan12'), ('Pertemuan13', 'Pertemuan13'), ('Pertemuan14', 'Pertemuan14'), ('Pertemuan15', 'Pertemuan15'), ('Pertemuan16', 'Pertemuan16')], default='Pertemuan1', max_length=20),
        ),
    ]
