# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0005_auto_20200923_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='File',
            field=models.FileField(default='oke', upload_to=''),
            preserve_default=False,
        ),
    ]
