# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-23 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0007_auto_20200923_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='Pertemuan',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], default='Pertemuan1', max_length=20),
        ),
    ]
