# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-24 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0013_auto_20200924_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='File',
            field=models.FileField(upload_to='static/media/Tugas'),
        ),
    ]
