# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-25 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0016_postmodel_filesoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='Filesoal',
            new_name='File_tugas',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='File',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='Fle_soal',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
