# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0017_auto_20200925_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='matakuliah',
            field=models.CharField(max_length=50),
        ),
    ]
