# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaaplikasi', models.CharField(max_length=200)),
                ('gambaraplikasi', models.ImageField(upload_to='')),
                ('contentaplikasi', models.TextField()),
            ],
        ),
    ]
