# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-24 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='gambaraplikasi',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
