# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-25 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0003_postmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='fileaplikasi',
            field=models.FileField(blank=True, upload_to='static/media/field'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='penjelasan',
            field=models.TextField(blank=True),
        ),
    ]
